# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.3-cli-stretch
        environment:
          DB_MASTER_DATABASE: app2019
          DB_MASTER_USERNAME: dbuser
          DB_MASTER_PASSWORD: dbpass

      - image: circleci/mysql:5.7

    steps:
      - checkout

      #- run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install mbstring pdo_mysql

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-composer-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-composer-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-composer-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      # run tests with phpunit or codecept
      - run: ./vendor/bin/phpunit -c phpunit_nodb.xml --coverage-html=$CIRCLE_ARTIFACTS
