version: '3'

services:
  db:
    build: ./mysql
    restart: always
    environment:
      MYSQL_DATABASE: app2019
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - 3306:3306
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql

  localstack:
    build: ./localstack
    restart: always
    environment:
      - SERVICES=sqs,sns,s3
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=ap-northeast-1
    #      - DATA_DIR=${DATA_DIR- }
    #      - PORT_WEB_UI=${PORT_WEB_UI- }
    ports:
      - 8080:8080
      - 4572:4572
      - 4576:4576
